version: "2"
services:
  # mysql storage
  db_mysql:
    image: mysql:5.7@sha256:4bc6bc963e6d8443453676cae56536f4b8156d78bae03c0145cbe47c2aad73bb
    restart: always
    ports:
    - 3306:3306
    volumes:
      - "./db_data/mysql:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: Profiler

  # postgresql storage
  db_pgsql:
    image: postgres@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
    restart: always
    ports:
    - 5432:5432
    volumes:
      - "./db_data/pg:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: Profiler

  web:
    restart: always
    build: 'docker/web'
    command:
      php -S 0.0.0.0:8000 -t src/www/ src/www/router.php
    ports:
    - "8000:8000"
    volumes:
    - .:/app
    - ./db_data:/app/db_data
